name: CI

on:
  push

jobs:
  check-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: install
        run: uv sync --all-groups
      - name: ruff check
        run: uv run ruff check green_melon
      - name: run format
        run: uv run ruff format --check green_melon
      - name: mypy
        run: uv run mypy green_melon
      - name: pytest
        run: uv run pytest tests